- Add tagged command for running specs by tag

diff --git a/respec b/respec
--- a/respec
+++ b/respec
@@ -26,10 +26,11 @@ respec_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Run full specs (default)\n" "$(green "all")        "
+  printf "  %s   Run all specs (default)\n" "$(green "all")        "
   printf "  %s   Run specs tagged with :focus\n" "$(green "focus")      "
-  printf "  %s   Run specs on files matching a pattern\n" "$(green "only")       "
-  printf "  %s   Run specs and exclude files matching a pattern\n" "$(green "except")     "
+  printf "  %s   Run specs only on files matching a pattern\n" "$(green "only")       "
+  printf "  %s   Run specs except files matching a pattern\n" "$(green "except")     "
+  printf "  %s   Run only specs that include/exclude certain tags\n" "$(green "tagged")     "
   printf "  %s   Run specs on files modified in the last N minutes\n" "$(green "last")       "
   printf "  %s   Run the last failed specs\n" "$(green "fails")      "
   printf "  %s   Continue from where the last run stopped\n" "$(green "continue")   "
@@ -72,9 +73,9 @@ respec_usage() {
 respec_all_usage() {
   if [[ -n $long_usage ]]; then
     printf "respec all\n\n"
-    printf "  Run full specs\n  \n  This is the default command. Running \`respec\` is the same as \`respec all\`.\n\n"
+    printf "  Run all specs\n  \n  This is the default command, so running \`respec\` is the same as \`respec all\`.\n\n"
   else
-    printf "respec all - Run full specs\n\n"
+    printf "respec all - Run all specs\n\n"
   fi
   printf "Alias: a\n"
   echo
@@ -92,11 +93,13 @@ respec_all_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -126,11 +129,13 @@ respec_focus_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -143,7 +148,7 @@ respec_focus_usage() {
 
 # :command.usage
 respec_only_usage() {
-  printf "respec only - Run specs on files matching a pattern\n\n"
+  printf "respec only - Run specs only on files matching a pattern\n\n"
   printf "Alias: o\n"
   echo
 
@@ -160,11 +165,13 @@ respec_only_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -180,12 +187,17 @@ respec_only_usage() {
     printf "    Partial filename\n"
     echo
 
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples:")"
+    printf "  $(blue \# run specs only on paths matching \'*integration*\')\n  respec only integration\n"
+    echo
+
   fi
 }
 
 # :command.usage
 respec_except_usage() {
-  printf "respec except - Run specs and exclude files matching a pattern\n\n"
+  printf "respec except - Run specs except files matching a pattern\n\n"
   printf "Alias: e\n"
   echo
 
@@ -202,11 +214,13 @@ respec_except_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -220,6 +234,60 @@ respec_except_usage() {
     # :argument.usage
     printf "  %s\n" "SEARCH"
     printf "    Partial filename\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples:")"
+    printf "  $(blue \# run specs only on paths not matching \'*examples*\')\n  respec except examples\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+respec_tagged_usage() {
+  printf "respec tagged - Run only specs that include/exclude certain tags\n\n"
+  printf "Alias: t, tag, tags\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  respec tagged TAG... [OPTIONS]\n"
+  printf "  respec tagged --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--watch, -w"
+    printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--repeat, -r"
+    printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "TAG..."
+    printf "    One or more tag names. Prefix with ~ to negate.\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples:")"
+    printf "  $(blue \# run specs tagged :production and not tagged :slow)\n  respec tagged production ~slow\n"
     echo
 
   fi
@@ -244,11 +312,13 @@ respec_last_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -287,11 +357,13 @@ respec_fails_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -321,11 +393,13 @@ respec_continue_usage() {
     # :flag.usage
     printf "  %s\n" "--watch, -w"
     printf "    Watch for change and rerun\n"
+    printf "    Conflicts: --repeat\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--repeat, -r"
     printf "    Wait for a key press after running and repeat\n"
+    printf "    Conflicts: --watch\n"
     echo
 
     # :command.usage_fixed_flags
@@ -629,15 +703,19 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'failures\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
   echo $'    \'continue\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'failures\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'except\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'tagged\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
@@ -653,10 +731,6 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'only\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
   echo $'    \'cont\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
@@ -665,15 +739,23 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'tags\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'only\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'tag\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'all\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'r\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'c\'*)'
+  echo $'    \'t\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
@@ -689,6 +771,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'c\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'f\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
@@ -697,8 +783,12 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --repeat --watch -h -r -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'r\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --version -h -v a all c completions cont continue e except f fails failures focus l last o only r refactor reset")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_respec_completions_filter "--help --version -h -v a all c completions cont continue e except f fails failures focus l last o only r refactor reset t tag tagged tags")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -787,6 +877,36 @@ respec_except_command() {
     # shellcheck disable=SC2046
     run_rspec $( (find . -name '*_spec.rb' -not -path "*$search*" | grep .) || echo "-tnothing")
   fi
+}
+
+# :command.function
+respec_tagged_command() {
+  # src/tagged_command.sh
+  watch="${args[--watch]}"
+  repeat="${args[--repeat]}"
+  tags=(${args[tag]})
+
+  # Clean up the tags array by replacing \\~ with \~
+  for i in "${!tags[@]}"; do
+    tags[$i]=${tags[$i]//\\~/\~}
+  done
+
+  # Zip the tags array with --tag prefix for each element
+  for tag in "${tags[@]}"; do
+    rspec_args+=(--tag "$tag")
+  done
+
+  if [[ $watch ]]; then
+    run_watch respec tagged "${tags[@]}"
+  elif [[ $repeat ]]; then
+    run_repeat respec tagged "${tags[@]}"
+  else
+    banner "tagged ${tags[*]}"
+    reset_status
+
+    run_rspec ${rspec_args[@]}
+  fi
+
 }
 
 # :command.function
@@ -932,6 +1052,13 @@ parse_requirements() {
       action="except"
       shift
       respec_except_parse_requirements "$@"
+      shift $#
+      ;;
+
+    tagged | t | tag | tags)
+      action="tagged"
+      shift
+      respec_tagged_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1405,6 +1532,114 @@ respec_except_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['search']+x} ]]; then
     printf "missing required argument: SEARCH\nusage: respec except SEARCH [OPTIONS]\n" >&2
+
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+respec_tagged_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        respec_tagged_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v rspec >/dev/null 2>&1; then
+    deps['rspec']="$(command -v rspec | head -n1)"
+  else
+    printf "missing dependency: rspec\n" >&2
+    printf "%s\n" "Install using $(magenta gem install rspec)" >&2
+    exit 1
+  fi
+
+  if command -v bundler >/dev/null 2>&1; then
+    deps['bundler']="$(command -v bundler | head -n1)"
+  else
+    printf "missing dependency: bundler\n" >&2
+    printf "%s\n" "Install using $(magenta gem install bundler)" >&2
+    exit 1
+  fi
+
+  if command -v filewatcher >/dev/null 2>&1; then
+    deps['filewatcher']="$(command -v filewatcher | head -n1)"
+  else
+    printf "missing dependency: filewatcher\n" >&2
+    printf "%s\n" "Install with $(magenta gem install filewatcher-cli)" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="tagged"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --watch | -w)
+        # :flag.conflicts
+        if [[ -n "${args['--repeat']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--repeat" >&2
+          exit 1
+        fi
+
+        # :flag.case_no_arg
+        args['--watch']=1
+        shift
+        ;;
+
+      # :flag.case
+      --repeat | -r)
+        # :flag.conflicts
+        if [[ -n "${args['--watch']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--watch" >&2
+          exit 1
+        fi
+
+        # :flag.case_no_arg
+        args['--repeat']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_repeatable
+        # :argument.case_repeatable
+        escaped="$(printf '%q' "$1")"
+        if [[ -z ${args['tag']+x} ]]; then
+          args['tag']="$escaped"
+        else
+          args['tag']="${args['tag']} $escaped"
+
+        fi
+        shift
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['tag']+x} ]]; then
+    printf "missing required argument: TAG\nusage: respec tagged TAG... [OPTIONS]\n" >&2
 
     exit 1
   fi
@@ -1916,6 +2151,7 @@ run() {
     "focus") respec_focus_command ;;
     "only") respec_only_command ;;
     "except") respec_except_command ;;
+    "tagged") respec_tagged_command ;;
     "last") respec_last_command ;;
     "fails") respec_fails_command ;;
     "continue") respec_continue_command ;;
