- Regenerate with bashly 1.1.7

diff --git a/respec b/respec
--- a/respec
+++ b/respec
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -489,7 +489,9 @@ inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -507,9 +509,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -635,6 +647,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'refactor\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'failures\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
@@ -643,12 +659,12 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'refactor\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
   echo $'    \'except\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'reset\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'focus\'*)'
@@ -659,15 +675,7 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'reset\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
   echo $'    \'only\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'last\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
@@ -675,23 +683,19 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'last\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'all\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'a\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
+  echo $'    \'r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'f\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'o\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'e\'*)'
+  echo $'    \'c\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
@@ -699,12 +703,20 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'c\'*)'
+  echo $'    \'e\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'r\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help -h")" -- "$cur" )'
+  echo $'    \'o\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'f\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'a\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_respec_completions_filter "--help --watch -h -w")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    *)'
@@ -887,6 +899,9 @@ parse_requirements() {
   # :command.environment_variables_default
   export RESPEC_STATUS_FILE="${RESPEC_STATUS_FILE:-spec/status.txt}"
   export RESPEC_HELPER_PATH="${RESPEC_HELPER_PATH:-spec/spec_helper.rb}"
+
+  env_var_names+=("RESPEC_STATUS_FILE")
+  env_var_names+=("RESPEC_HELPER_PATH")
 
   # :command.command_filter
   action=${1:-}
@@ -1215,7 +1230,6 @@ respec_only_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['search']+x} ]]; then
-
           args['search']=$1
           shift
         else
@@ -1303,7 +1317,6 @@ respec_except_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['search']+x} ]]; then
-
           args['search']=$1
           shift
         else
@@ -1391,12 +1404,6 @@ respec_last_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['min']+x} ]]; then
-          # :argument.validations
-          if [[ -n $(validate_integer "$1") ]]; then
-            printf "validation error in %s:\n%s\n" "MIN" "$(validate_integer "$1")" >&2
-            exit 1
-          fi
-
           args['min']=$1
           shift
         else
@@ -1411,6 +1418,13 @@ respec_last_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['min']:-} ]] || args['min']="10"
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['min'] && -n $(validate_integer "${args['min']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "MIN" "$(validate_integer "${args['min']:-}")" >&2
+    exit 1
+  fi
 
 }
 
@@ -1763,6 +1777,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
